"""
WO4 acceptance test: make_row / aggregate_band_t regression against step3b TSVs.

Run from repo root:
    python scripts/edop/areas/test_engine_wo4.py

Acceptance (from WO4 work order):
  1. Numeric regression: representative_raw, n_units, coverage, year, epoch_year,
     p10/p90/sd (extracted from detail) match step3b_block7_primary.tsv within tol.
  2. Caveat mechanism (Pin 2): LMR rows carry caveat=['lmr_caveat']; HYDE 1950 rows
     carry caveat=['hyde_caveat']; other rows carry []. assemble_payload emits the
     text once at top level.
  3. HYDE 1950 round-trip: wide span (1900–2000) surfaces the 1950 artifact caveat.
  4. Lean projection: project_row strips 'detail'; full projection includes it.
  5. Status vocabulary: all rows status ∈ {ok, no_data, outside_active_domain}.

Note on known deltas from the TSV:
  - The notebook's aggregate_band_t did NOT apply lmr_caveat to LMR rows (missing arg
    in _row calls in Cell 13). The engine fixes this; the TSV's lmr_caveat column
    is therefore NaN even for LMR rows. Test 2 verifies the corrected behavior.
  - The test fixture uses the rounded Timbuktu coordinates from the step3b notebook
    (LAT=16.8167, LON=-2.9833), not the WHG-resolved precise coordinates
    (16.76618535, -3.00777252). Using precise coords gives a different buffer (~4 km
    shift) with 425 cells vs the TSV's 426, and ~11% different HYDE means. WO4b
    confirmed this is coordinate choice, not a code bug — the engine is deterministic.
  - The TSV has columns lmr_caveat/hyde_caveat (text); the engine uses caveat key-refs.
    Those TSV columns are excluded from the numeric diff; the mechanism is verified
    separately in Test 2/3.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import pandas as pd
import scripts.shared.db_utils as _dbu
from scripts.shared.db_utils import db_connect
from scripts.edop.areas.engine import (
    aggregate_band_t, assemble_payload, project_row, diff_output, CAVEAT_TEXTS,
)

ROOT = Path(_dbu.__file__).resolve().parents[2]
OUT  = ROOT / 'output' / 'edop' / 'areas'

# Notebook coordinates (step3b Cell 1: LAT=16.8167, LON=-2.9833).
# These match the frozen Band T TSVs exactly.  The WHG-resolved precise
# coordinates (16.76618535, -3.00777252) differ by ~4 km and capture a
# slightly different HYDE cell set — that difference is what WO4b diagnosed.
LAT       = 16.8167
LON       = -2.9833
RADIUS_KM = 100.0
FROM_YEAR = 1100
TO_YEAR   = 1200

VALID_STATUSES = {'ok', 'no_data', 'outside_active_domain'}


def flatten_rows(rows):
    """
    Flatten list of make_row dicts to a DataFrame for TSV comparison.

    - Extracts p10/p90/sd from the detail sub-block onto the row.
    - Renames 'coverage' → 'coverage_weight' to match the TSV column name.
    """
    flat = []
    for r in rows:
        d = {k: v for k, v in r.items() if k not in ('detail', 'caveat')}
        d['coverage_weight'] = d.pop('coverage', None)
        for k in ('p10', 'p90', 'sd'):
            d[k] = r.get('detail', {}).get(k)
        flat.append(d)
    return pd.DataFrame(flat)


# Columns present in both engine output (flattened) and the reference TSV
_COMPARE_COLS = [
    'variable', 'method', 'unit_type', 'n_units', 'representative_raw',
    'year', 'epoch_year', 'coverage_weight', 'p10', 'p90', 'sd',
]


def _run_primary(conn):
    return aggregate_band_t(LAT, LON, RADIUS_KM, FROM_YEAR, TO_YEAR, conn)


def test_regression(conn):
    """Test 1: strict numeric regression against step3b_block7_primary.tsv.

    The TSV was generated by the step3b notebook using the rounded Timbuktu
    coordinates (LAT=16.8167, LON=-2.9833).  The test fixture uses the same
    coordinates, so HYDE, LMR, and eVolv2k rows all match exactly (float_tol=0.01).
    """
    print('─' * 60)
    print('Test 1: numeric regression (primary span 1100–1200)')
    print('─' * 60)

    rows   = _run_primary(conn)
    actual = flatten_rows(rows).sort_values(['year', 'variable']).reset_index(drop=True)
    ref    = pd.read_csv(OUT / 'step3b_block7_primary.tsv', sep='\t')
    ref    = ref.sort_values(['year', 'variable']).reset_index(drop=True)

    ok = diff_output(
        actual[_COMPARE_COLS],
        ref[_COMPARE_COLS],
        float_tol=0.01,
        id_col=None,
        label='primary 1100–1200 strict',
    )
    return ok


def test_caveat_mechanism(conn):
    """Test 2: caveat key-refs on rows; text assembled once at payload level."""
    print()
    print('─' * 60)
    print('Test 2: caveat mechanism (Pin 2)')
    print('─' * 60)

    rows = _run_primary(conn)
    ok   = True

    lmr_rows   = [r for r in rows if r['method'] == 'grid_areal_collapsed']
    hyde_rows  = [r for r in rows if r['method'] == 'grid_areal_distribution']
    evolv_rows = [r for r in rows if r['method'] == 'global_forcing']

    bad = [r for r in lmr_rows if 'lmr_caveat' not in r.get('caveat', [])]
    if bad:
        print(f'  FAIL  {len(bad)}/{len(lmr_rows)} LMR rows missing lmr_caveat key')
        ok = False
    else:
        print(f'  OK    {len(lmr_rows)} LMR rows carry [\'lmr_caveat\']')

    bad = [r for r in hyde_rows if r.get('caveat', []) != []]
    if bad:
        print(f'  FAIL  {len(bad)} HYDE rows (no 1950 in span) have non-empty caveat')
        ok = False
    else:
        print(f'  OK    {len(hyde_rows)} HYDE rows carry []  (no 1950 in span)')

    bad = [r for r in evolv_rows if r.get('caveat', []) != []]
    if bad:
        print(f'  FAIL  {len(bad)} eVolv2k rows have non-empty caveat')
        ok = False
    else:
        print(f'  OK    {len(evolv_rows)} eVolv2k rows carry []')

    payload  = assemble_payload(
        rows, neighborhood={}, shortfall=0.0, bands=['T'],
        temporal={'from_year': FROM_YEAR, 'to_year': TO_YEAR},
    )
    expected = {'lmr_caveat'}
    got      = set(payload['caveats'].keys())
    if got != expected:
        print(f'  FAIL  top-level caveats: got {got}, expected {expected}')
        ok = False
    else:
        print(f'  OK    assemble_payload caveats: {sorted(got)}')

    for k in payload['caveats']:
        if payload['caveats'][k] != CAVEAT_TEXTS[k]:
            print(f'  FAIL  caveat text mismatch for {k!r}')
            ok = False

    print('  PASS  caveat mechanism' if ok else '  FAIL  caveat mechanism')
    return ok


def test_hyde_1950_caveat(conn):
    """Test 3: wide span (1900–2000) surfaces hyde_caveat on epoch 1950 rows."""
    print()
    print('─' * 60)
    print('Test 3: hyde_caveat at 1950 (wide span 1900–2000)')
    print('─' * 60)

    rows = aggregate_band_t(LAT, LON, RADIUS_KM, 1900, 2000, conn)
    ok   = True

    hyde_1950 = [r for r in rows
                 if r['method'] == 'grid_areal_distribution'
                 and r.get('epoch_year') == 1950]
    if not hyde_1950:
        print('  FAIL  no HYDE rows at epoch_year=1950 in span 1900–2000')
        return False

    bad = [r for r in hyde_1950 if 'hyde_caveat' not in r.get('caveat', [])]
    if bad:
        print(f'  FAIL  {len(bad)}/{len(hyde_1950)} HYDE 1950 rows missing hyde_caveat')
        ok = False
    else:
        print(f'  OK    {len(hyde_1950)} HYDE epoch-1950 rows carry [\'hyde_caveat\']')

    payload = assemble_payload(
        rows, neighborhood={}, shortfall=0.0, bands=['T'],
        temporal={'from_year': 1900, 'to_year': 2000},
    )
    if 'hyde_caveat' not in payload['caveats']:
        print("  FAIL  hyde_caveat missing from top-level caveats")
        ok = False
    else:
        print("  OK    assemble_payload caveats include 'hyde_caveat'")

    print('  PASS  hyde_caveat at 1950' if ok else '  FAIL  hyde_caveat at 1950')
    return ok


def test_lean_projection(conn):
    """Test 4: project_row strips detail in lean; carries it in full."""
    print()
    print('─' * 60)
    print('Test 4: lean vs. full projection')
    print('─' * 60)

    rows     = _run_primary(conn)
    hyde_row = next(r for r in rows if r['method'] == 'grid_areal_distribution')

    lean = project_row(hyde_row, include_detail=False)
    full = project_row(hyde_row, include_detail=True)

    print(f"\n  Lean ({len(lean)} fields — no detail):")
    for k, v in lean.items():
        print(f"    {k:30s} = {v!r}")

    print(f"\n  Full (detail block):")
    print(f"    detail = {full.get('detail')}")

    ok = ('detail' not in lean
          and 'detail' in full
          and full['detail'].get('p10') is not None)
    print()
    if ok:
        print('  PASS  lean omits detail; full carries p10/p90/sd')
    else:
        print('  FAIL  projection error')
    return ok


def test_status_values(conn):
    """Test 5: all status values conform to Pin 1 vocabulary."""
    print()
    print('─' * 60)
    print('Test 5: status vocabulary (Pin 1)')
    print('─' * 60)

    rows = _run_primary(conn)
    bad  = [r for r in rows if r['status'] not in VALID_STATUSES]
    if bad:
        vals = {r['status'] for r in bad}
        print(f'  FAIL  unexpected status values: {vals}')
        return False
    print(f'  OK    all {len(rows)} rows status ∈ {VALID_STATUSES}')
    print('  PASS  status vocabulary')
    return True


if __name__ == '__main__':
    conn    = db_connect()
    results = [
        test_regression(conn),
        test_caveat_mechanism(conn),
        test_hyde_1950_caveat(conn),
        test_lean_projection(conn),
        test_status_values(conn),
    ]
    conn.close()

    print()
    print('=' * 60)
    n_pass = sum(results)
    print(f"WO4: {'PASS' if all(results) else 'FAIL'}  "
          f"({n_pass}/{len(results)} tests passed)")
    sys.exit(0 if all(results) else 1)
