"""Regenerate docsite/api.md from the live public API surface -- the routes marked
include_in_schema=True in app/main.py, the same filter Swagger itself uses. Parameter
tables are built from each route's actual function signature (name/type/required/
default -- read straight from the code, can't drift out of sync with it) plus
per-parameter descriptions parsed from each route's own numpydoc-style docstring
"Parameters" section. Response-shape prose is pulled from each docstring's "Response"
section. Hand-authored intro/example/notes content lives in this script's constants,
not in api.md directly.

Re-run whenever a public route's signature, docstring, or schema-visibility changes.

Usage: python3 scripts/edop/docsite/generate_api_guide.py
"""
import inspect
import re
import sys
import typing
from pathlib import Path

from fastapi.params import Param  # base class of Query/Path/Body -- has is_required()/default

ROOT = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(ROOT))
API_MD = ROOT / "docsite" / "api.md"

from app.main import app  # noqa: E402 -- importing app.main does not run lifespan/DB connect

PAGE_HEAD = """<!-- Generated by scripts/edop/docsite/generate_api_guide.py -- do not
     hand-edit the endpoint sections below; edit this script's constants and each
     route's own docstring instead, then re-run. -->
# API Guide

EDOPS — the Environmental Dimensions of Place Service — generates structured
environmental signatures for a coordinate, a buffer/basin-ring scope, or a
historical polity's territory. Signatures are derived from global datasets aggregated
at the hydrological sub-basin level in [BasinATLAS](https://www.hydrosheds.org/products/hydroatlas),
with optional historical enrichment from LMR v2.1 (paleoclimate), eVolv2k v4 (volcanic
events), and HYDE 3.4 (land use).

**Base URL:** `https://edops.computingplace.org/api`<br>
**Interactive schema:** [edops.computingplace.org/api/schema](https://edops.computingplace.org/api/schema)<br>
**A full worked example payload:** [edops_schema.json](/documentation/edops_schema.json)

> Research prototype. The API is publicly accessible but not under a stability
> guarantee — parameters and response fields may change between versions.

This page documents the endpoints below, and only those — every other route this app
serves exists to support the Sandbox/Explorer/Workbench pages directly and isn't
public API surface (hidden from the interactive schema accordingly).

## Local vs. upstream

Many Band A–D fields appear as pairs: a local value (the sub-basin only) and an
upstream value (its entire contributing watershed, to the headwaters). Upstream keys
carry an `_upstream` suffix, e.g. `aridity` / `aridity_upstream`.

Aggregation depends on the variable: intensive quantities — aridity, precipitation,
temperature, soils, slope — are area-weighted averages over the catchment; extensive
quantities like river area and reservoir volume are sums. See each variable's
[Codebook](codebook.md) entry for its rule. A few variables, like discharge, have no
upstream counterpart at all — their local value is already the integrated result of
everything above.

The divergence between local and upstream is usually the meaningful reading, not the
upstream value alone: a desert city fed by a distant mountain river occupies a
qualitatively different position than one where the two converge. Because the upstream
figure spans the whole catchment, it can blend very different terrain into one number
— read it against its local counterpart. The API returns both raw values; it does not
compute or return the divergence itself.

Full variable-by-variable reference: see the [Codebook](codebook.md).

## Endpoints

"""

EXAMPLES_SECTION = """## Example requests

**Bands A and B only — Athens**
```
curl "https://edops.computingplace.org/api/signature?lat=37.97&lon=23.73&bands=AB"
```

**Full baseline signature — Samarkand**
```
curl "https://edops.computingplace.org/api/signature?lat=39.65&lon=66.98&bands=ABCDE"
```

**With historical climate — Rome, early imperial period**
```
curl "https://edops.computingplace.org/api/signature?lat=41.9&lon=12.5&bands=ABCT&from_year=1&to_year=400"
```

**Flat mode — all fields as top-level keys**
```
curl "https://edops.computingplace.org/api/signature?lat=16.8167&lon=-2.9833&bands=ABCDE&flat=true"
```

**Areal signature for a polity — Northern Song at 1080 CE**
```
curl "https://edops.computingplace.org/api/area?polity=Northern%20Song&year=1080&bands=ABCDE"
```

**Buffer scope via the scope dispatcher**
```
curl "https://edops.computingplace.org/api/areas?scope=buffer&lat=16.8167&lon=-2.9833&radius_km=100&bands=ABCDE"
```

"""

NOTES_SECTION = """## Notes for application developers

- **`/area` vs `/areas`:** not a clean singular/plural pair. `/area` is polity-only.
  `/areas` dispatches on `scope`, and its four resolver types aren't all "areas" in the
  geometric sense — `single_basin` and `polity` are bounded regions, `buffer` is an
  arbitrary radius, and `basin_ring` is a topological set of neighboring basins, not a
  shape at all. "Area" in EDOPS currently covers several distinct things; not yet
  normalized to one term.
- **CORS:** Cross-origin requests are allowed — call the API directly from browser JavaScript.
- **No basin found:** If the coordinate falls outside all known sub-basins (open
  ocean, ice sheet), the API returns HTTP 404.
- **Response modes:** By default, environmental variables are grouped under
  `profile_groups`. Pass `&flat=true` on `/signature` to receive all variable values
  as flat top-level keys instead.
- **Band T availability:** `_status` reflects whether the Band T mechanism ran, not
  whether every source had data — LMR, eVolv2k, and HYDE each have independent
  coverage windows, and a single query can mix available and unavailable sources.
  Check the per-source fields (`lmr_status`, the `*_note` fields) rather than
  `_status` alone. See [edops_schema.json](/documentation/edops_schema.json)
  for a full worked example.
- **`level` default varies by endpoint, deliberately left as-is** — `/signature`
  defaults to `8`; `/area` and `/areas` default to `6`. `/signature` always returns a
  single basin's data regardless of level, so this only affects resolution, not
  payload shape or size. Pass it explicitly if your use case depends on which
  sub-basin resolution you get.
- **Rate limits:** None enforced currently.

---

*EDOPS is part of the [Computing Place](https://computingplace.org) research initiative.*
*Contact: karl.geog@gmail.com*
"""


def parse_docstring(doc):
    """Split a numpydoc-style docstring into (summary, {param: description}, response_text)."""
    if not doc:
        return "", {}, ""
    doc = inspect.cleandoc(doc)
    lines = doc.split("\n")

    summary_lines = []
    i = 0
    while i < len(lines) and lines[i].strip() not in ("Parameters", "Response"):
        summary_lines.append(lines[i])
        i += 1
    summary = " ".join(l.strip() for l in summary_lines if l.strip())

    params = {}
    response_lines = []
    section = None
    current_param = None
    while i < len(lines):
        stripped = lines[i].strip()
        if stripped in ("Parameters", "Response"):
            section = stripped
            i += 2  # skip header + its ---- underline
            current_param = None
            continue
        if section == "Parameters":
            m = re.match(r"^([\w.]+(?:\s*,\s*[\w.]+)*)\s*:\s*(.*)$", stripped)
            if m:
                names = [n.strip() for n in m.group(1).split(",")]
                current_param = names
                for name in names:
                    params[name] = m.group(2)
            elif stripped and current_param:
                for name in current_param:
                    params[name] += " " + stripped
        elif section == "Response":
            response_lines.append(lines[i])
        i += 1

    return summary, params, "\n".join(response_lines).strip()


def format_annotation(annotation):
    if annotation is inspect.Parameter.empty:
        return "—"
    origin = typing.get_origin(annotation)
    if origin is typing.Union:  # Optional[X] == Union[X, None]
        args = [a for a in typing.get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return getattr(args[0], "__name__", str(args[0]))
    return getattr(annotation, "__name__", str(annotation))


def format_range(p):
    """Render any ge/le/gt/lt constraints from a Query()/Path()/Body() wrapper, e.g. '-90 to 90'."""
    d = p.default
    if not isinstance(d, Param):
        return ""
    lo = hi = None
    for m in d.metadata:
        if hasattr(m, "ge"):
            lo = m.ge
        elif hasattr(m, "gt"):
            lo = m.gt
        elif hasattr(m, "le"):
            hi = m.le
        elif hasattr(m, "lt"):
            hi = m.lt
    if lo is not None and hi is not None:
        return f"{lo} to {hi}"
    return ""


def _required_and_default(p):
    """Resolve (required, default_value) for a parameter -- handles plain defaults
    (or none) as well as FastAPI Query()/Path()/Body() wrappers, whose own .default
    is the FieldInfo object itself, not the value Swagger actually uses."""
    d = p.default
    if isinstance(d, Param):
        required = d.is_required()
        return required, (None if required else d.default)
    if d is inspect.Parameter.empty:
        return True, None
    return False, d


def format_default(required, default):
    if required or default is None:
        return "—"
    if isinstance(default, bool):
        return "`true`" if default else "`false`"
    return f"`{default}`"


def endpoint_params(fn):
    sig = inspect.signature(fn)
    # Fallback only -- prefer each Query()'s own .description (the standard OpenAPI
    # parameter field) once a route has been migrated to it; docstring "Parameters"
    # parsing remains for routes that haven't been converted yet.
    _, docstring_descriptions, _ = parse_docstring(fn.__doc__)
    out = []
    for name, p in sig.parameters.items():
        required, default = _required_and_default(p)
        type_str = format_annotation(p.annotation)
        rng = format_range(p)
        if rng:
            type_str += f" ({rng})"
        query_description = p.default.description if isinstance(p.default, Param) else None
        out.append({
            "name": name,
            "type": type_str,
            "required": required,
            "default": format_default(required, default),
            "description": query_description or docstring_descriptions.get(name, ""),
        })
    return out


def param_table(params):
    if not params:
        return ""
    rows = ["| Parameter | Type | Required | Default | Description |",
            "|---|---|---|---|---|"]
    for p in params:
        req = "**yes**" if p["required"] else "no"
        rows.append(f"| `{p['name']}` | {p['type']} | {req} | {p['default']} | {p['description']} |")
    return "\n".join(rows) + "\n\n"


# Hand-ordered rather than alphabetical -- /signature is the core, heavily-parameterized
# endpoint and reads best first; anything not listed here sorts alphabetically after.
ENDPOINT_ORDER = ["/api/signature", "/api/area", "/api/areas", "/api/health"]


def public_routes():
    """Routes marked include_in_schema=True -- the same filter Swagger itself uses."""
    out = []
    for route in app.routes:
        if not hasattr(route, "endpoint"):
            continue
        if not getattr(route, "include_in_schema", False):
            continue
        if not route.path.startswith("/api/"):
            continue
        out.append(route)

    def sort_key(r):
        try:
            return (0, ENDPOINT_ORDER.index(r.path))
        except ValueError:
            return (1, r.path)

    return sorted(out, key=sort_key)


def main():
    routes = public_routes()
    print(f"Found {len(routes)} public route(s): {[r.path for r in routes]}")

    content = [PAGE_HEAD]
    for route in routes:
        methods = sorted(m for m in route.methods if m != "HEAD")
        summary, _, response = parse_docstring(route.endpoint.__doc__)
        params = endpoint_params(route.endpoint)

        content.append(f"### `{'/'.join(methods)} {route.path}`\n\n")
        if summary:
            content.append(f"{summary}\n\n")
        content.append(param_table(params))
        if response:
            content.append(f"**Response**\n\n```text\n{response}\n```\n\n")

    content.append(EXAMPLES_SECTION)
    content.append(NOTES_SECTION)

    API_MD.write_text("".join(content))
    print(f"Wrote {API_MD}")


if __name__ == "__main__":
    main()
