"""Regenerate the mechanical "## The bands" section of docsite/codebook.md from the
canonical variable catalog. Hand-written prose (page intro, band-level lead sentences,
"Derived variables" TODO block) is preserved — only the per-band Category/Variable
listings are regenerated. Re-run whenever documentation/EDOPS_variable_catalog_v0.4.tsv
changes.

Usage: python3 scripts/edop/docsite/generate_codebook.py
"""
import csv
from collections import defaultdict, Counter
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent.parent
CATALOG = ROOT / "documentation" / "EDOPS_variable_catalog_v0.4.tsv"
CODEBOOK = ROOT / "docsite" / "codebook.md"

BAND_ORDER = ["A", "B", "C", "D", "E", "T"]
BAND_NAMES = {
    "A": "Physiographic",
    "B": "Hydroclimatic",
    "C": "Bioclimatic",
    "D": "Anthropocene",
    "E": "Coastality",
    "T": "Temporal",
}
# Hand-authored lead sentence per band — edit here, not in codebook.md directly.
BAND_INTROS = {
    "A": "Stable over geological timescales; defensible as a historical baseline for any period.",
    "B": "Hydrological fluxes and soil characteristics integrating the full upstream catchment "
         "under the current climatic regime. Discharge and runoff reflect contemporary "
         "conditions, including the effects of upstream dams and diversions where present.",
    "C": "Contemporary climate baseline from BasinATLAS (WorldClim ~1970–2000 CE). These are "
         "long-run averages — for historical temperature and precipitation, Band T provides "
         "LMR anomalies relative to a 20th-century reference.",
    "D": "Present-day only. Exclude or qualify for pre-modern analyses; useful as a contrast "
         "baseline.",
    "E": "Hydrological connectivity to the marine outlet.",
    "T": "Period-specific climate enrichment from LMR v2.1, volcanic event annotation from "
         "eVolv2k v4, and land-use history from HYDE 3.4. Requires from_year and to_year.",
}

SU_LABELS = {"s": "local only", "s+u": "local + upstream", "point": "point value"}

PAGE_HEAD = """<!-- Generated by scripts/edop/docsite/generate_codebook.py — do not hand-edit
     "## The bands" section below; edit BAND_INTROS in that script instead, then re-run. -->
# EDOPS Codebook

The Codebook is a strict per-variable reference. See [Reading a signature](sandbox/reading-a-signature.md) for explanation of their display in the Sandbox Signature tab.

BasinATLAS-sourced variables link to their own page in the provider's catalog rather than
being re-described here — each links to its specific attribute page; the full catalog
(<a href="/documentation/BasinATLAS_Catalog_v10.pdf" target="_blank">BasinATLAS_Catalog_v10.pdf ↗</a>)
is also linkable directly, for browsing rather than looking up one variable.

## Local, upstream, and delta

*TODO — extend the existing API Guide paragraph (`docsite/api.md`, "Local vs. upstream" section).*

## The bands

"""

DERIVED_SECTION = """## Derived variables

*TODO — rationale and computation for each `source: Derived` row (e.g. `coast_fraction`, `relief_range_m`, `relief_position`, `outlet_type`). Flagged in the TODO as "the one unavoidable hand-written block."*

"""

OTHER_HEADER = """## Other / not yet banded

*Rows in the catalog outside the A–E/T band structure — not part of the `/api/signature` response today.*

"""

ABBR_DEFS = (
    "*[implemented]: Live in the current API and signature payload\n"
    "*[planned]: Named in the catalog but not yet in the live API\n"
)


def load_rows():
    with open(CATALOG, newline="") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def dimension_title(dim):
    return "(Uncategorized)" if not dim else dim.replace("_", " ").title()


def variable_block(row, fold_source, dominant_source):
    name = row["friendly_name"]
    key = row["schema_key"]
    status = row["status"]
    source = row["source"]
    units = row["units"]
    su = SU_LABELS.get(row["s_u"], "")
    notes = row["notes"].strip()
    atlas_id = row["atlas_id"].strip()

    parts = [status]
    if not (fold_source and source == dominant_source):
        parts.append(source)
    if units:
        parts.append(units)
    if su:
        parts.append(su)

    desc = notes if notes else "*No description yet in the catalog — needs a hand-written note.*"
    if source == "BasinATLAS v1.0" and atlas_id:
        desc += (f' <a href="/static/basinatlas_pages/{atlas_id}.pdf" target="_blank">'
                 f"BasinATLAS source page ({atlas_id}) ↗</a>")
    return f"**{name}** (`{key}`) — {' · '.join(parts)}<br>\n{desc}\n\n"


def band_section(band, rows):
    n = len(rows)
    n_impl = sum(1 for r in rows if r["status"] == "implemented")
    n_plan = n - n_impl

    src_counts = Counter(r["source"] for r in rows)
    dominant_source, dominant_count = src_counts.most_common(1)[0]
    fold_source = dominant_count / n >= 0.5

    intro = BAND_INTROS[band]
    tail = (
        f" {n} variables in the catalog ({n_impl} implemented, {n_plan} planned), all sourced "
        f"from {dominant_source} unless noted otherwise below."
        if fold_source
        else f" {n} variables in the catalog ({n_impl} implemented, {n_plan} planned)."
    )

    out = [f"### Band {band} — {BAND_NAMES[band]}\n\n{intro}{tail}\n\n"]

    by_dim = defaultdict(list)
    for r in rows:
        by_dim[dimension_title(r["dimension"])].append(r)

    for dim in sorted(by_dim, key=lambda d: (d == "(Uncategorized)", d)):
        out.append(f"#### {dim}\n\n")
        for r in sorted(by_dim[dim], key=lambda r: r["friendly_name"]):
            out.append(variable_block(r, fold_source, dominant_source))

    return "".join(out)


def other_section(rows):
    if not rows:
        return ""
    out = [OTHER_HEADER]
    by_dim = defaultdict(list)
    for r in rows:
        by_dim[dimension_title(r["dimension"])].append(r)
    for dim in sorted(by_dim):
        for r in sorted(by_dim[dim], key=lambda r: r["friendly_name"]):
            out.append(variable_block(r, fold_source=False, dominant_source=None))
    return "".join(out)


def main():
    rows = load_rows()
    by_band = defaultdict(list)
    for r in rows:
        by_band[r["band"]].append(r)

    content = [PAGE_HEAD]
    for band in BAND_ORDER:
        content.append(band_section(band, by_band.get(band, [])))
    content.append(DERIVED_SECTION)
    content.append(other_section(by_band.get("output", [])))
    content.append(ABBR_DEFS)

    CODEBOOK.write_text("".join(content))
    print(f"Wrote {CODEBOOK} ({sum(len(v) for v in by_band.values())} variable rows)")


if __name__ == "__main__":
    main()
